version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      AZURE_KEYVAULT_URI: https://${KEY_VAULT_NAME_REPLACED_BY_GITHUBACTION}.vault.azure.net/
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID_REPLACED_BY_GITHUBACTION}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET_REPLACED_BY_GITHUBACTION}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID_REPLACED_BY_GITHUBACTION}
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: nicedpsdb
      MYSQL_HOST: mockDB

    volumes:
      - .:/src
      - /src/node_modules
      - ./coverage:/src/coverage
      - ./oss:/src/oss
  
    depends_on:
      - "database"
  
  database:
    container_name: mockDB
    image: mysql:8.0
    volumes:
      - ./.github/sql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nicedpsdb
    ports:
      - "3306:3306"