name: 001 deploy infra

env:
  AZ_CLI_VERSION: 2.30.0

on:
  workflow_dispatch:
    inputs:
      subscription_code:
        description: "SUBSCRIPTION_CODE of resources to be deployed. This value is also used as the github secret env value. (e.g. gcspre, gcsrls):"
        required: true
        default: gcspre
      region_code:
        description: "REGION_CODE of resources to be deployed (e.g. japaneast):"
        required: true
        default: japaneast
      env_name:
        description: "ENV_NAME of resources to be deployed (e.g. prd, sdv, dev):"
        required: true
        default: dev
      app_code:
        description: "APP_CODE of resources to be deployed (usually do not need to change from lacmn):"
        required: true
        default: lacmn
      st_rg_name:
        description: "[RESTORE] RG name of the backup Storage Account.
          (e.g. rg-gcspre-cmn-lacmn-st-blob-agw-backup):"
        required: false
        default: ""
      restore_file_name:
        description: "[RESTORE] File name to be restored.
          (e.g. ARMBK{YYYYmmddHHMMSS}-{AGW_RG_NAME}.json; [default: latest]):"
        required: false
        default: ""
      force_update_flag:
        type: boolean
        description: "When building AGW, do you forcibly process even if RG already exists? "
        required: false
        default: "false"

jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.subscription_code }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: STEP 100
        uses: azure/CLI@v1
        with:
          azcliversion: ${{ env.AZ_CLI_VERSION }}
          inlineScript: |
            bash ./azure/deployments/100-deploy-lacmn-key-vault.sh \
              "${{ github.event.inputs.env_name }}" \
              "${{ github.event.inputs.region_code }}" \
              "${{ github.event.inputs.subscription_code }}" \
              "${{ github.event.inputs.app_code }}"

      - name: STEP 101
        uses: azure/CLI@v1
        with:
          azcliversion: ${{ env.AZ_CLI_VERSION }}
          inlineScript: |
            bash ./azure/deployments/101-deploy-sql-secret-settings.sh \
              "${{ github.event.inputs.subscription_code }}" \
              "${{ github.event.inputs.region_code }}" \
              "${{ github.event.inputs.env_name }}" \
              "${{ github.event.inputs.app_code }}"

      - name: STEP 102
        uses: azure/CLI@v1
        with:
          azcliversion: ${{ env.AZ_CLI_VERSION }}
          inlineScript: |
            bash ./azure/deployments/102-deploy-vnet-sql-cr-resources.sh \
              "${{ github.event.inputs.subscription_code }}" \
              "${{ github.event.inputs.region_code }}" \
              "${{ github.event.inputs.env_name }}" \
              "${{ github.event.inputs.app_code }}"

      - name: STEP 103
        uses: azure/CLI@v1
        with:
          azcliversion: ${{ env.AZ_CLI_VERSION }}
          inlineScript: |
            bash ./azure/deployments/103-deploy-github-secret-settings.sh \
              "${{ github.event.inputs.subscription_code }}" \
              "${{ github.event.inputs.region_code }}" \
              "${{ github.event.inputs.env_name }}" \
              "${{ github.event.inputs.app_code }}"

      - name: STEP 104
        uses: azure/CLI@v1
        with:
          azcliversion: ${{ env.AZ_CLI_VERSION }}
          inlineScript: |
            bash ./azure/deployments/104-deploy-agw-resources.sh \
              "${{ github.event.inputs.subscription_code }}" \
              "${{ github.event.inputs.region_code }}" \
              "${{ github.event.inputs.env_name }}" \
              "${{ github.event.inputs.app_code }}" \
              "${{ github.event.inputs.st_rg_name }}" \
              "${{ github.event.inputs.restore_file_name }}" \
              "${{ github.event.inputs.force_update_flag }}"

      - name: STEP 105
        uses: azure/CLI@v1
        with:
          azcliversion: ${{ env.AZ_CLI_VERSION }}
          inlineScript: |
            bash ./azure/deployments/105-deploy-lacmn-app-auth-settings.sh \
              "${{ github.event.inputs.env_name }}" \
              "${{ github.event.inputs.subscription_code }}" \
              "${{ github.event.inputs.app_code }}"

      - name: STEP 106
        uses: azure/CLI@v1
        with:
          azcliversion: ${{ env.AZ_CLI_VERSION }}
          inlineScript: |
            bash ./azure/deployments/106-deploy-aks-resources.sh \
              "${{ github.event.inputs.env_name }}" \
              "${{ github.event.inputs.region_code }}" \
              "${{ github.event.inputs.subscription_code }}" \
              "${{ github.event.inputs.app_code }}"

      - name: Send Notification to slack
        if: always()
        uses: tokorom/action-slack-incoming-webhook@master
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
            text: "***Infra Creation Completed*** [${{ github.repository }}] @ ${{ github.event_name }} "
            attachments: |
              [
                {
                  "author_name": "${{ github.actor }}",
                  "author_icon": "${{ github.event.sender.avatar_url }}",
                  "fields": [
                    {
                      "title": "GitHub Actions URL",
                      "value": "https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]   
